#!/usr/bin/env python3
"""
Mrki Database Manager
Handles database connections, schema management, and multi-database support
"""

import os
import json
from pathlib import Path
from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass, field
from enum import Enum
from abc import ABC, abstractmethod


class DatabaseType(Enum):
    """Supported database types"""
    POSTGRESQL = "postgresql"
    MYSQL = "mysql"
    SQLITE = "sqlite"
    MONGODB = "mongodb"
    REDIS = "redis"
    COCKROACHDB = "cockroachdb"


@dataclass
class DatabaseConfig:
    """Database connection configuration"""
    db_type: DatabaseType
    host: str = "localhost"
    port: int = 5432
    database: str = ""
    username: str = ""
    password: str = ""
    ssl_mode: str = "prefer"
    pool_size: int = 10
    timeout: int = 30
    url: Optional[str] = None
    options: Dict[str, Any] = field(default_factory=dict)
    
    def get_connection_string(self) -> str:
        """Generate connection string"""
        if self.url:
            return self.url
        
        if self.db_type == DatabaseType.POSTGRESQL:
            return f"postgresql://{self.username}:{self.password}@{self.host}:{self.port}/{self.database}?sslmode={self.ssl_mode}"
        elif self.db_type == DatabaseType.MYSQL:
            return f"mysql://{self.username}:{self.password}@{self.host}:{self.port}/{self.database}"
        elif self.db_type == DatabaseType.SQLITE:
            return f"sqlite:///{self.database}"
        elif self.db_type == DatabaseType.MONGODB:
            return f"mongodb://{self.username}:{self.password}@{self.host}:{self.port}/{self.database}"
        elif self.db_type == DatabaseType.REDIS:
            auth = f":{self.password}@" if self.password else ""
            return f"redis://{auth}{self.host}:{self.port}/{self.database}"
        else:
            raise ValueError(f"Unsupported database type: {self.db_type}")


@dataclass
class MigrationRecord:
    """Database migration record"""
    version: str
    name: str
    applied_at: str
    checksum: str
    execution_time_ms: int


class DatabaseManager:
    """Main database management class"""
    
    def __init__(self, config: Optional[DatabaseConfig] = None):
        self.config = config
        self.migrations_path = Path("migrations")
        self.seeders_path = Path("seeders")
    
    def create_config_from_env(self, prefix: str = "DB") -> DatabaseConfig:
        """Create database config from environment variables"""
        db_type_str = os.getenv(f"{prefix}_TYPE", "postgresql").lower()
        
        try:
            db_type = DatabaseType(db_type_str)
        except ValueError:
            db_type = DatabaseType.POSTGRESQL
        
        default_ports = {
            DatabaseType.POSTGRESQL: 5432,
            DatabaseType.MYSQL: 3306,
            DatabaseType.MONGODB: 27017,
            DatabaseType.REDIS: 6379,
            DatabaseType.SQLITE: 0,
        }
        
        return DatabaseConfig(
            db_type=db_type,
            host=os.getenv(f"{prefix}_HOST", "localhost"),
            port=int(os.getenv(f"{prefix}_PORT", default_ports.get(db_type, 5432))),
            database=os.getenv(f"{prefix}_NAME", "myapp"),
            username=os.getenv(f"{prefix}_USER", "postgres"),
            password=os.getenv(f"{prefix}_PASSWORD", ""),
            ssl_mode=os.getenv(f"{prefix}_SSL_MODE", "prefer"),
            pool_size=int(os.getenv(f"{prefix}_POOL_SIZE", "10")),
            url=os.getenv(f"{prefix}_URL"),
        )
    
    def generate_schema(self, tables: List[Dict[str, Any]], 
                        db_type: DatabaseType = DatabaseType.POSTGRESQL) -> str:
        """Generate SQL schema from table definitions"""
        generators = {
            DatabaseType.POSTGRESQL: self._generate_postgres_schema,
            DatabaseType.MYSQL: self._generate_mysql_schema,
            DatabaseType.SQLITE: self._generate_sqlite_schema,
        }
        
        generator = generators.get(db_type, self._generate_postgres_schema)
        return generator(tables)
    
    def _generate_postgres_schema(self, tables: List[Dict[str, Any]]) -> str:
        """Generate PostgreSQL schema"""
        lines = [
            "-- PostgreSQL Schema",
            "-- Generated by Mrki Database Manager",
            "",
            "-- Enable UUID extension",
            "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";",
            "",
        ]
        
        for table in tables:
            lines.append(f"-- Table: {table['name']}")
            lines.append(f"CREATE TABLE IF NOT EXISTS {table['name']} (")
            
            columns = []
            for col in table.get('columns', []):
                col_def = self._generate_postgres_column(col)
                columns.append(f"    {col_def}")
            
            # Add default timestamps
            columns.append("    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
            columns.append("    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP")
            
            lines.append(",\n".join(columns))
            lines.append(");")
            
            # Add indexes
            for index in table.get('indexes', []):
                lines.append(self._generate_postgres_index(table['name'], index))
            
            lines.append("")
        
        # Add foreign keys
        for table in tables:
            for fk in table.get('foreign_keys', []):
                lines.append(self._generate_postgres_foreign_key(table['name'], fk))
            
            lines.append("")
        
        return "\n".join(lines)
    
    def _generate_postgres_column(self, col: Dict[str, Any]) -> str:
        """Generate PostgreSQL column definition"""
        name = col['name']
        col_type = col['type']
        
        type_map = {
            'string': 'VARCHAR(255)',
            'text': 'TEXT',
            'integer': 'INTEGER',
            'bigint': 'BIGINT',
            'float': 'REAL',
            'decimal': 'DECIMAL(10, 2)',
            'boolean': 'BOOLEAN',
            'datetime': 'TIMESTAMP WITH TIME ZONE',
            'date': 'DATE',
            'uuid': 'UUID DEFAULT uuid_generate_v4()',
            'json': 'JSONB',
            'array': 'TEXT[]',
        }
        
        pg_type = type_map.get(col_type, 'VARCHAR(255)')
        
        constraints = []
        if col.get('primary_key'):
            constraints.append('PRIMARY KEY')
        if col.get('unique'):
            constraints.append('UNIQUE')
        if col.get('required', True) and not col.get('primary_key'):
            constraints.append('NOT NULL')
        if col.get('default') is not None:
            constraints.append(f"DEFAULT {col['default']}")
        
        constraint_str = ' '.join(constraints)
        return f"{name} {pg_type} {constraint_str}".strip()
    
    def _generate_postgres_index(self, table_name: str, index: Dict[str, Any]) -> str:
        """Generate PostgreSQL index"""
        name = index.get('name', f"idx_{table_name}_{'_'.join(index['columns'])}")
        columns = ', '.join(index['columns'])
        unique = "UNIQUE " if index.get('unique') else ""
        
        return f"CREATE {unique}INDEX IF NOT EXISTS {name} ON {table_name} ({columns});"
    
    def _generate_postgres_foreign_key(self, table_name: str, fk: Dict[str, Any]) -> str:
        """Generate PostgreSQL foreign key"""
        name = fk.get('name', f"fk_{table_name}_{fk['column']}")
        column = fk['column']
        ref_table = fk['references_table']
        ref_column = fk.get('references_column', 'id')
        on_delete = fk.get('on_delete', 'CASCADE')
        
        return f"""ALTER TABLE {table_name}
    ADD CONSTRAINT {name}
    FOREIGN KEY ({column})
    REFERENCES {ref_table}({ref_column})
    ON DELETE {on_delete};"""
    
    def _generate_mysql_schema(self, tables: List[Dict[str, Any]]) -> str:
        """Generate MySQL schema"""
        lines = [
            "-- MySQL Schema",
            "-- Generated by Mrki Database Manager",
            "",
        ]
        
        for table in tables:
            lines.append(f"CREATE TABLE IF NOT EXISTS {table['name']} (")
            
            columns = []
            for col in table.get('columns', []):
                col_def = self._generate_mysql_column(col)
                columns.append(f"    {col_def}")
            
            columns.append("    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
            columns.append("    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
            
            lines.append(",\n".join(columns))
            lines.append(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;")
            lines.append("")
        
        return "\n".join(lines)
    
    def _generate_mysql_column(self, col: Dict[str, Any]) -> str:
        """Generate MySQL column definition"""
        name = col['name']
        col_type = col['type']
        
        type_map = {
            'string': 'VARCHAR(255)',
            'text': 'TEXT',
            'integer': 'INT',
            'bigint': 'BIGINT',
            'float': 'FLOAT',
            'decimal': 'DECIMAL(10, 2)',
            'boolean': 'BOOLEAN',
            'datetime': 'DATETIME',
            'date': 'DATE',
            'uuid': 'CHAR(36)',
            'json': 'JSON',
        }
        
        mysql_type = type_map.get(col_type, 'VARCHAR(255)')
        
        constraints = []
        if col.get('primary_key'):
            constraints.append('PRIMARY KEY AUTO_INCREMENT')
        if col.get('unique'):
            constraints.append('UNIQUE')
        if col.get('required', True) and not col.get('primary_key'):
            constraints.append('NOT NULL')
        
        constraint_str = ' '.join(constraints)
        return f"{name} {mysql_type} {constraint_str}".strip()
    
    def _generate_sqlite_schema(self, tables: List[Dict[str, Any]]) -> str:
        """Generate SQLite schema"""
        lines = [
            "-- SQLite Schema",
            "-- Generated by Mrki Database Manager",
            "",
            "PRAGMA foreign_keys = ON;",
            "",
        ]
        
        for table in tables:
            lines.append(f"CREATE TABLE IF NOT EXISTS {table['name']} (")
            
            columns = []
            for col in table.get('columns', []):
                col_def = self._generate_sqlite_column(col)
                columns.append(f"    {col_def}")
            
            columns.append("    created_at DATETIME DEFAULT CURRENT_TIMESTAMP")
            columns.append("    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP")
            
            lines.append(",\n".join(columns))
            lines.append(");")
            lines.append("")
        
        return "\n".join(lines)
    
    def _generate_sqlite_column(self, col: Dict[str, Any]) -> str:
        """Generate SQLite column definition"""
        name = col['name']
        col_type = col['type']
        
        type_map = {
            'string': 'TEXT',
            'text': 'TEXT',
            'integer': 'INTEGER',
            'bigint': 'INTEGER',
            'float': 'REAL',
            'decimal': 'REAL',
            'boolean': 'INTEGER',
            'datetime': 'TEXT',
            'date': 'TEXT',
            'uuid': 'TEXT',
            'json': 'TEXT',
        }
        
        sqlite_type = type_map.get(col_type, 'TEXT')
        
        constraints = []
        if col.get('primary_key'):
            constraints.append('PRIMARY KEY AUTOINCREMENT')
        if col.get('unique'):
            constraints.append('UNIQUE')
        if col.get('required', True) and not col.get('primary_key'):
            constraints.append('NOT NULL')
        
        constraint_str = ' '.join(constraints)
        return f"{name} {sqlite_type} {constraint_str}".strip()
    
    def generate_mongodb_schema(self, collections: List[Dict[str, Any]]) -> str:
        """Generate MongoDB schema (JavaScript)"""
        lines = [
            "// MongoDB Schema",
            "// Generated by Mrki Database Manager",
            "",
            "const mongoose = require('mongoose');",
            "",
        ]
        
        for collection in collections:
            name = collection['name']
            lines.append(f"// {name} Schema")
            lines.append(f"const {name}Schema = new mongoose.Schema({{")
            
            for field in collection.get('fields', []):
                schema_def = self._generate_mongoose_field(field)
                lines.append(f"    {schema_def}")
            
            lines.append("    createdAt: { type: Date, default: Date.now },")
            lines.append("    updatedAt: { type: Date, default: Date.now },")
            lines.append("}, {")
            lines.append("    timestamps: true,")
            lines.append("});")
            lines.append("")
            
            # Add indexes
            for index in collection.get('indexes', []):
                fields = ', '.join([f"{f}: 1" for f in index['fields']])
                unique = ", unique: true" if index.get('unique') else ""
                lines.append(f"{name}Schema.index({{ {fields} }}{unique});")
            
            lines.append("")
            lines.append(f"module.exports = mongoose.model('{name}', {name}Schema);")
            lines.append("")
        
        return "\n".join(lines)
    
    def _generate_mongoose_field(self, field: Dict[str, Any]) -> str:
        """Generate Mongoose field definition"""
        name = field['name']
        field_type = field['type']
        
        type_map = {
            'string': 'String',
            'text': 'String',
            'integer': 'Number',
            'bigint': 'Number',
            'float': 'Number',
            'decimal': 'Number',
            'boolean': 'Boolean',
            'datetime': 'Date',
            'date': 'Date',
            'uuid': 'String',
            'json': 'mongoose.Schema.Types.Mixed',
            'array': '[mongoose.Schema.Types.Mixed]',
            'object': 'mongoose.Schema.Types.Mixed',
        }
        
        mongoose_type = type_map.get(field_type, 'String')
        
        options = [f"type: {mongoose_type}"]
        if field.get('required'):
            options.append("required: true")
        if field.get('unique'):
            options.append("unique: true")
        if field.get('default') is not None:
            options.append(f"default: {field['default']}")
        if field.get('index'):
            options.append("index: true")
        
        return f"{name}: {{ {', '.join(options)} }},"
    
    def generate_redis_schema(self, key_patterns: List[Dict[str, Any]]) -> str:
        """Generate Redis key patterns documentation"""
        lines = [
            "# Redis Schema",
            "# Generated by Mrki Database Manager",
            "",
            "## Key Patterns",
            "",
        ]
        
        for pattern in key_patterns:
            lines.append(f"### {pattern['name']}")
            lines.append(f"- **Pattern**: `{pattern['pattern']}`")
            lines.append(f"- **Type**: {pattern.get('type', 'string')}")
            lines.append(f"- **TTL**: {pattern.get('ttl', 'none')} seconds")
            lines.append(f"- **Description**: {pattern.get('description', '')}")
            lines.append("")
            
            if 'example' in pattern:
                lines.append(f"**Example**: `{pattern['example']}`")
                lines.append("")
        
        return "\n".join(lines)
    
    def create_migration(self, name: str, up_sql: str, down_sql: str) -> Path:
        """Create a new migration file"""
        import datetime
        
        self.migrations_path.mkdir(parents=True, exist_ok=True)
        
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        filename = f"{timestamp}_{name}.sql"
        filepath = self.migrations_path / filename
        
        content = f"""-- Migration: {name}
-- Created at: {datetime.datetime.now().isoformat()}

-- Up Migration
{up_sql}

-- Down Migration
-- {down_sql}
"""
        filepath.write_text(content)
        return filepath
    
    def generate_erd(self, tables: List[Dict[str, Any]], format: str = "mermaid") -> str:
        """Generate Entity Relationship Diagram"""
        if format == "mermaid":
            return self._generate_mermaid_erd(tables)
        elif format == "dbml":
            return self._generate_dbml_erd(tables)
        else:
            raise ValueError(f"Unsupported ERD format: {format}")
    
    def _generate_mermaid_erd(self, tables: List[Dict[str, Any]]) -> str:
        """Generate Mermaid ERD"""
        lines = ["erDiagram"]
        
        for table in tables:
            lines.append(f"    {table['name']} {{")
            for col in table.get('columns', []):
                pk = "PK" if col.get('primary_key') else ""
                fk = "FK" if col.get('foreign_key') else ""
                key = " ".join(filter(None, [pk, fk]))
                lines.append(f"        {col['type']} {col['name']} {key}")
            lines.append("    }")
        
        # Relationships
        for table in tables:
            for fk in table.get('foreign_keys', []):
                lines.append(f"    {table['name']} ||--o{{ {fk['references_table']} : has")
        
        return "\n".join(lines)
    
    def _generate_dbml_erd(self, tables: List[Dict[str, Any]]) -> str:
        """Generate DBML (Database Markup Language)"""
        lines = []
        
        for table in tables:
            lines.append(f"Table {table['name']} {{")
            
            for col in table.get('columns', []):
                modifiers = []
                if col.get('primary_key'):
                    modifiers.append("pk")
                if col.get('unique'):
                    modifiers.append("unique")
                if col.get('required'):
                    modifiers.append("not null")
                
                mod_str = f" [{', '.join(modifiers)}]" if modifiers else ""
                lines.append(f"  {col['name']} {col['type']}{mod_str}")
            
            lines.append("}")
            lines.append("")
        
        # Relationships
        for table in tables:
            for fk in table.get('foreign_keys', []):
                lines.append(f"Ref: {table['name']}.{fk['column']} > {fk['references_table']}.{fk.get('references_column', 'id')}")
        
        return "\n".join(lines)
    
    def generate_seed_data(self, table_name: str, count: int = 10) -> List[Dict[str, Any]]:
        """Generate seed data for a table"""
        from faker import Faker
        
        fake = Faker()
        records = []
        
        for i in range(count):
            record = {
                "id": i + 1,
                "created_at": fake.iso8601(),
                "updated_at": fake.iso8601(),
            }
            records.append(record)
        
        return records
    
    def validate_schema(self, schema: str, db_type: DatabaseType = DatabaseType.POSTGRESQL) -> Dict[str, Any]:
        """Validate SQL schema"""
        # Basic validation - in production, use actual database parser
        errors = []
        warnings = []
        
        # Check for common issues
        if "CREATE TABLE" not in schema.upper():
            warnings.append("No CREATE TABLE statements found")
        
        if "PRIMARY KEY" not in schema.upper():
            warnings.append("No PRIMARY KEY constraints found")
        
        # Check for reserved keywords
        reserved = ["user", "order", "group", "select", "insert", "update", "delete"]
        for keyword in reserved:
            if f" {keyword} " in schema.lower():
                warnings.append(f"Potential reserved keyword usage: {keyword}")
        
        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings,
        }


if __name__ == "__main__":
    # Example usage
    manager = DatabaseManager()
    
    tables = [
        {
            "name": "users",
            "columns": [
                {"name": "id", "type": "uuid", "primary_key": True},
                {"name": "email", "type": "string", "unique": True, "required": True},
                {"name": "name", "type": "string", "required": True},
                {"name": "password", "type": "string", "required": True},
            ],
            "indexes": [
                {"columns": ["email"], "unique": True},
            ],
        },
        {
            "name": "posts",
            "columns": [
                {"name": "id", "type": "uuid", "primary_key": True},
                {"name": "title", "type": "string", "required": True},
                {"name": "content", "type": "text"},
                {"name": "user_id", "type": "uuid", "required": True},
            ],
            "foreign_keys": [
                {"column": "user_id", "references_table": "users", "on_delete": "CASCADE"},
            ],
        },
    ]
    
    schema = manager.generate_schema(tables, DatabaseType.POSTGRESQL)
    print(schema)
